version: '3'

services:
  web:
    container_name: web
    build: ./web
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway
  wgadmin:
    container_name: wgadmin
    build: ./wgadmin
    volumes:
      - ./wgadmin/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=justinholsclaw.com
      - VALIDATION=http
      - STAGING=false
      - SUBDOMAINS=www, wgadmin
    volumes:
      - /swag:/config
      - ./ops/nginx.conf:/config/nginx/site-confs/default
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=justin_admin
      - POSTGRES_PASSWORD=justin_admin
      - POSTGRES_DB=production_db
    ports:
      - "5432:5432"
    volumes:
      # - ./script.sql:/docker-entrypoint-initdb.d/creationscript.sql
      - /data/postgres:/var/lib/postgresql/data/
