version: '3'

services: 
  web:
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  api:
    build: ./api
    ports:
      - 5000:5000
  wgadmin:
    build: ./wgadmin
    ports:
      - 8081:80
    volumes:
      - ./wgadmin/default.conf:/etc/nginx/conf.d/default.conf      

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=justinholsclaw.com
      - VALIDATION=http
      - STAGING=true
      - SUBDOMAINS=www, wgadmin
    volumes:
      - /swag:/config
      - /ops/nginx.conf:/config/nginx/site-confs/default/default
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
