name: "deploy"

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0
      - name: test
        run: |
          docker run --rm -v $(pwd)/web:/app -w /app node:14 npm i
          docker run --rm -v $(pwd)/web:/app -w /app node:14 npm run ops:test
      - name: build
        run: docker-compose up --build -d

      - name: run API
        run: |
          dotnet publish api
          sudo systemctl restart PortfolioApi.service
          